### ISSUE TITLE
Improve pipeline

### ISSUE THREAD

**Issue by patheard** [dtf-ein/dtf-ein.github.io#17]
# Accessibility testing
- Use cucumber-puppeteeer with node-puppeteer image.
- Simple package.json with local dev server that serves generated `_site` directory.

# Performance
- Cache gem and node_modules between pipeline runs.

```yaml
# Gems
      - save_cache:
          key: deps-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

# Node
      - save_cache:
          key: deps-node-{{ checksum "package.json" }}
          paths:
            - node_modules
```
